# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FMDB' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FMDB
pod 'FMDB', '~> 2.7.2'
end
